// This file is generated by Prismic local builder. Update with care!

export { default as Carousel } from './Carousel'
export { default as Footer } from './Footer'
export { default as Navbar } from './Navbar'
export { default as PostsGostar } from './PostsGostar'
export { default as PostsInclua } from './PostsInclua'
export { default as PostsRecentes } from './PostsRecentes'
export { default as SectionAgendar } from './SectionAgendar'
export { default as SectionCadastro } from './SectionCadastro'
